feat: add chromium to :all

diff --git a/Dockerfile-all.template b/Dockerfile-all.template
--- a/Dockerfile-all.template
+++ b/Dockerfile-all.template
@@ -1,23 +1,35 @@
 ${TEMPLATE_BUILDER}
 
-FROM debian:stable-slim
-RUN set -ex; \
-	apt-get update; \
-	DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y \
+FROM zenika/alpine-chrome
+# All things back to root: https://github.com/Zenika/alpine-chrome/blob/master/Dockerfile
+USER root
+RUN set -e; \
+	apk add --no-cache \
+	tini \
+	bash \
 	curl \
 	rsync \
 	openssh-client \
-	dnsutils \
+	bind-tools \
 	jq \
+# In the mean time, install all famous script languages
 	python3 \
 	php \
-	nodejs npm \
+	nodejs nodejs-npm \
 	ruby \
-	lua5.3 \
+	lua5.3
+
+# Essentials for scripts
+# playwright: https://github.com/Zenika/alpine-chrome/blob/master/with-playwright/Dockerfile
+ENV PLAYWRIGHT_SKIP_BROWSER_DOWNLOAD=1 \
+	PLAYWRIGHT_CHROMIUM_EXECUTABLE_PATH=/usr/bin/chromium-browser \
+	NODE_PATH=/usr/lib/node_modules
+RUN set -e; \
+	if [ "/usr/lib/node_modules" != "$(npm root -g)" ]; then \
+	echo >&2 "NODE_PATH invalid" && exit 2; \
+	fi \
 	; \
-	apt-get clean; \
-	rm -rf /var/lib/apt/lists/*
-RUN set -ex; \
-	npm -g install npm \
-	npm prune
+	npm -g install playwright-chromium
+
+ENTRYPOINT ["tini", "--"]
 ${TEMPLATE_FACADE}
